[workspace]
members = [ 
    "crates/nvm",
    "crates/nvm-test-utils",
    "crates/runtime",

    "crates/lang/nebula_lexer",
    "crates/lang/nebula_ast", "crates/lang/nebula_parser",
]
resolver = "3"
