[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
nvm = { path = "../nvm" }

[[bin]]
name = "nvm"
path = "src/main.rs"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }